### ISSUE TITLE
the scrutinizer setup is useless as it does not run anything

### ISSUE THREAD

**Issue by stof** [whiteoctober/WhiteOctoberPagerfantaBundle#122]
Scrutinizer checks are not enabled on Scrutinizer, making the build useless. you should enable analysis tools

**Comment by pablodip** [comment]
What should I do? Scrutinizer was already receiving events: https://scrutinizer-ci.com/g/whiteoctober/WhiteOctoberPagerfantaBundle/settings/incoming-events

**Comment by stof** [comment]
you should enable scrutinizer checks, either in a scrutinizer.yml file or in the scrutinizer UI

**Comment by pablodip** [comment]
I have just added this to this config file:

```
checks:
    php: true
```

Should that be enough? Scrutinizer's configuration and documentation are a mess. :S

**Comment by stof** [comment]
yeah, their configuration doc is weird. It should work.

Btw, the scrutinizer status is not reported either on PRs. You may need to give it access and go to scrutinizer to regenerate a github token.

**Comment by pablodip** [comment]
I've just regenerated the GitHub token, but it has not asked me for any new permissions. Doesn't it require permissions from the organisation like Travis does?

**Comment by stof** [comment]
@pablodip yeah, because this is a restriction set on github side, making the token unable to access some organizations

**Comment by pablodip** [comment]
How can that be done? That was done automatically when logging in on Travis, but I have no idea how that works on Scrutinizer. :S (Scrutinizer should use quality usability inspections :)).

**Comment by pablodip** [comment]
@richsage Could you possibly have a look at WhiteOctober's permissions?

**Comment by richsage** [comment]
I think this is done now - see https://scrutinizer-ci.com/g/whiteoctober/WhiteOctoberPagerfantaBundle/
