### ISSUE TITLE
new stable tag?

### ISSUE THREAD

**Issue by acasademont** [whiteoctober/WhiteOctoberPagerfantaBundle#124]
A new stable tag would come handy after all the deprecation removal patches commited in the last days. Thanks! :D

**Comment by pkruithof** [comment]
Yes please!

**Comment by sampart** [comment]
Hi @acasademont and @pkruithof.  I've now created a new release tag - https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/releases/tag/v1.0.4

Thanks,

Sam Partington
Technical Lead (Backend Engineering), White October

**Comment by acasademont** [comment]
Thanks @sampart much apreciated ;)
