### ISSUE TITLE
Add Bootstrap 4 view

### ISSUE THREAD

**Issue by JHGitty** [whiteoctober/WhiteOctoberPagerfantaBundle#126]
Add view for Bootstrap 4.

**Comment by tdubuffet** [comment]
+1

**Comment by bogdaniel** [comment]
+1

**Comment by sampart** [comment]
To get a Bootstrap4 view, we need someone to finish off this PR: https://github.com/whiteoctober/Pagerfanta/pull/206.  The remaining tasks are listed in my comment on there.

(This might help if someone does pick it up: http://stackoverflow.com/questions/5884784/how-to-pull-remote-branch-from-somebody-elses-repo)

**Comment by sampart** [comment]
This has now been done in https://github.com/whiteoctober/Pagerfanta/pull/226, and I've created a new Pagerfanta release for it: https://github.com/whiteoctober/Pagerfanta/releases/tag/v1.0.5

I'm going to close this issue.  If anyone has specific problems using the new Bootstrap 4 view with the PagerfantaBundle, then feel free to open an issue for that.
