### ISSUE TITLE
Pagerfanta for Symfony 3.0

### ISSUE THREAD

**Issue by kironet** [whiteoctober/WhiteOctoberPagerfantaBundle#129]
When will be pagerfanta available for symfony2 3.0? Thanks

**Comment by pablodip** [comment]
Done on #130

**Comment by kironet** [comment]
So, how to install pagerfanta to sf 3.0?
After composer require white-october/pagerfanta-bundle
I got error. 
[error.txt](https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/files/53950/error.txt)
