### ISSUE TITLE
Pagerfanta - Symfony 3.0 / Can't install

### ISSUE THREAD

**Issue by kironet** [whiteoctober/WhiteOctoberPagerfantaBundle#133]
So, how to install pagerfanta for sf 3.0?
After composer require white-october/pagerfanta-bundle
I got [error.txt](https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/files/54555/error.txt)

Thanks

**Comment by sstok** [comment]
Try using the dev-master. Symfony 3.0 is supported in the master version.

**Comment by pablodip** [comment]
Just tagged a new release: https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/releases/tag/v1.0.5
