### ISSUE TITLE
Customising the layout of Pagerfanta pagination with a custom template

### ISSUE THREAD

**Issue by crmpicco** [whiteoctober/WhiteOctoberPagerfantaBundle#138]
I have Pagerfanta installed and working, however I am having difficulty in customising the layout. I read in the [docs][1] that I need to pass through `my_template`, however I am unsure where this should be configured and what specifically this refers to.

**Custom template**

If you want to use a custom template, add another argument

    <div class="pagerfanta">
        {{ pagerfanta(my_pager, 'my_template') }}
    </div>

Ideally I would like to have my own Twig template that I can modify, however I don’t know if Pagerfanta supports this. Is it all done in PHP?

  [1]: https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle#custom-template

**Comment by crmpicco** [comment]
Answer provided here: http://stackoverflow.com/a/35507413/691505 if anyone comes here.

**Comment by sampart** [comment]
Thanks for linking through to that, @crmpicco.  Sorry that no-one from here was able to answer sooner!
