### ISSUE TITLE
Problem with "omitFirstPage: true" - can't navigate to first page.

### ISSUE THREAD

**Issue by Chrysweel** [whiteoctober/WhiteOctoberPagerfantaBundle#158]
Hello.

I want to delete first page of pagination.
I do not want to have duplicate routes.
/resources and /resources?page=1

I try param {{ pagerfanta(my_pager, 'default', { 'omitFirstPage': true}) }}

but so button of one page in pagination, go to page 2. And it is imposible navigate to first page.
Any idea ?
I need include some more ?

Thanks in advance!

**Comment by sampart** [comment]
@Chrysweel I've changed the title of this ticket to better reflect the problem you're describing.  (I think you forgot to change it when editing the ticket to talk about a different problem to your original one.)  I'll try and get some time to investigate the problem itself, too ;-)

**Comment by sampart** [comment]
@Chrysweel I've tested this here using the example Twig function call you gave me and it seems to be okay.  Can you show me the relevant code from your controller please?

**Comment by xawiers** [comment]
You can just revert this file commit:
https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/commit/dfe64b79846f29cc5becd034c5d2942e32e141e5?diff=unified

**Comment by sampart** [comment]
Thanks all for your input here.  This is now fixed in https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/releases/tag/v1.1.1

(FYI @phibo23)
