### ISSUE TITLE
 How to '' guess '' page number

### ISSUE THREAD

**Issue by marvin-SL** [whiteoctober/WhiteOctoberPagerfantaBundle#162]
I have my paginated items.  10 max per page. 

I want to go to item 35 but I don't know in advance on what page is this item :
www.foobar.com/item#id_35

And I want pagerFanta to return me :
www.foobar.com/page/3/item#id_35

How to return the  page of this item ?

**Comment by sampart** [comment]
Could you just do this?

`$page = ceil($itemNum / $pagerfanta->getMaxPerPage())`

(`ceil(35/10)` gives you `4`, for example)

(Note, `ceil` returns a `float`.  This will normally be fine, but cast it to an `int` if not.)

**Comment by marvin-SL** [comment]
Hello, 
I did someting like this earlier,  it works but I thought pager fanta would already have a function for my needs. If not i'll stick with this. 
Thank You

**Comment by olorton** [comment]
I'm closing this issue as it should be on the main Pagerfanta project, see: https://github.com/whiteoctober/Pagerfanta/issues/234
