### ISSUE TITLE
Repository description incorrect

### ISSUE THREAD

**Issue by rpkamp** [whiteoctober/WhiteOctoberPagerfantaBundle#177]
The description of this repository is `Bundle to use Pagerfanta with Symfony2.`, which would suggest that it won't work for Symfony 3 and 4.
Since it does work on Symfony 3 and 4 I would suggest changing the description of this repository to prevent people from going away thinking this bundle is not for them.

**Comment by olorton** [comment]
Fixed, thanks for highlighting this.
