### ISSUE TITLE
Remove tests from autoloading

### ISSUE THREAD

**Issue by SpacePossum** [whiteoctober/WhiteOctoberPagerfantaBundle#185]
```
    "autoload": {
        "psr-4": { "WhiteOctober\\PagerfantaBundle\\": "" }
    },
```

causes something like:

```

$ ./app/console
PHP Fatal error:  Cannot declare class AppKernel, because the name is already in use in /var/www/FooBar/vendor/white-october/pagerfanta-bundle/TestsProject/app/AppKernel.php on line 24
PHP Stack trace:
PHP   1. Symfony\Component\Debug\ErrorHandler->handleException() /var/www/FooBar/vendor/symfony/debug/ErrorHandler.php:0
PHP   2. Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler->handleError() /var/www/FooBar/vendor/symfony/debug/ErrorHandler.php:533
PHP   3. Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler->getClassCandidates() /var/www/FooBar/vendor/symfony/debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php:62
PHP   4. Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler->findClassInPath() /var/www/FooBar/vendor/symfony/debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php:118
PHP   5. Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler->convertFileToClass() /var/www/FooBar/vendor/symfony/debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php:136
```

is it possible to remove the `Tests` and `TestsProject` from the `autoload` (maybe move to `autoload-dev` or extend the `tests.php` bootstrap file in the root) and maybe add those to `.gitignore` ?

**Comment by sstok** [comment]
This only happens when you generate a class-map, you can add an `exclude-from-classmap` for this.

```json
"autoload": {
    "psr-4": { "WhiteOctober\\PagerfantaBundle\\": "" }
},
"exclude-from-classmap": [
    "Tests",
    "TestsProject"
]
```

And it's generally recommended to use a .gitattribute (which is properly what @SpacePossum meant 😉 ):

```
/Tests export-ignore
/TestsProject export-ignore
```

Which also makes the distribution file much smaller.

**Comment by delboy1978uk** [comment]
We are stuck on v1.0.0 because of this

**Comment by delboy1978uk** [comment]
FYI, I fixed it by manually specifying which AppKernel class to use (our one!)
```json
"autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
```
But seriously, your test stuff should not interfere like this! Give that file a namespace! :-D

**Comment by sampart** [comment]
@SpacePossum thanks for your involvement with this so far.  You're right that the project is suffering from a lack of available time on our behalf.  If you were able to create a PR, that would be great.  Sorry not to have had more time to look at this one.

**Comment by BackEndTea** [comment]
> And it's generally recommended to use a .gitattribute

This is true, but it won't stop the  `Tests` folder etc from appearing if someone runs composer with `--prefer-source`, of if it has trouble getting the distributed version, and it uses the source as a fall-back.

**Comment by sampart** [comment]
This is now fixed in release https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/releases/tag/v1.1.3.

**Comment by SpacePossum** [comment]
close as this is fixed :)

**Comment by sampart** [comment]
Thanks!
