### ISSUE TITLE
Call from PHP templates?

### ISSUE THREAD

**Issue by biji** [whiteoctober/WhiteOctoberPagerfantaBundle#187]
How to call pagerfanta() from PHP template?

**Comment by biji** [comment]
My workaround is call render from php template to render other action containing twig pagerfanta()
```
echo $view['actions']->render(new \Symfony\Component\HttpKernel\Controller\ControllerReference....)
```

**Comment by sampart** [comment]
Since so much here depends on the TwigExtension, PHP templates aren't supported.  I'm glad you've found a way of making them work for you, though.
