### ISSUE TITLE
Incorrect translate "previous"

### ISSUE THREAD

**Issue by SkyAgency** [whiteoctober/WhiteOctoberPagerfantaBundle#188]
In file View/DefaultTranslatedView.php:

```
protected function previousMessageOption()
    {
        return 'previous_message';
    }
```

to

```
protected function previousMessageOption()
    {
        return 'prev_message';
    }
```

**Comment by SkyAgency** [comment]
In file View/DefaultTranslatedView.php:

```
protected function previousMessageOption()
    {
        return 'previous_message';
    }
```

to

```
protected function previousMessageOption()
    {
        return 'previous_message';
    }
```

**Comment by sampart** [comment]
Related: https://github.com/whiteoctober/Pagerfanta/issues/219

**Comment by sampart** [comment]
This will be fixed once https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/pull/194 is merged.

**Comment by sampart** [comment]
#194 has been merged.  This is fixed.

**Comment by sampart** [comment]
Related release: https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/releases/tag/v1.2.1
