### ISSUE TITLE
Not added to bundles.php in Symfony 4 - getting Unknown “pagerfanta” function

### ISSUE THREAD

**Issue by charlesastwood** [whiteoctober/WhiteOctoberPagerfantaBundle#197]
Updating to Symfony 4 from 3.4 I started getting 

Unknown “pagerfanta” function

After ages trying to work out how to fix I noticed in bundles.php there was no entry for PagerfantaBundle

Adding this line to bottom fixed:

    WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle::class => ['all' => true],

Shouldn't this be done automatically? Or documented

**Comment by sampart** [comment]
Thank you for contributing, @charlesastwood - I'd totally missed this.

We'd need to set up a Symfony Flex recipe to do this automatically, so I've created issue #198 for that.

In the meantime, I've created https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/pull/199 to update the documentation for manually updating that file.

Thanks again.
