### ISSUE TITLE
Unknown "pagerfanta" function. in symfony 4.1

### ISSUE THREAD

**Issue by cezar62882** [whiteoctober/WhiteOctoberPagerfantaBundle#201]

**Comment by u-mulder** [comment]
Maybe you can provide __more detailed__ description?

**Comment by sampart** [comment]
@cezar62882 does the change described in https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/issues/197 solve this for you?  Thanks

**Comment by cezar62882** [comment]
Sorry, I forgot to configure buddle in config.
