### ISSUE TITLE
Pagerfanta ArrayAdapter ; add text in view 

### ISSUE THREAD

**Issue by nfouka** [whiteoctober/WhiteOctoberPagerfantaBundle#204]
I have an array that contains 3 type of information, I would like to display a pagination with pagerfanta on the same page and add a text to separate
example: entities = ('info11' ,,,,, 'info19', 'info22', .... info29 ')
expected display

  <1 2 3>
 
**'INFORMATION 1'**
info11
info12

info15

info 5
**'INFORMATION 2'**
Info21
info22

info26

do you have an idea how to adapt it with symfony please?

**Comment by sampart** [comment]
You'll probably need some clever templating logic here, assigning the items to different arrays.

The basic approach is simply to loop over the items and output them:

```twig
{% for item in my_pager.currentPageResults %}
    <ul>
        <li>{{ item.id }}</li>
    </ul>
{% endfor %}
```
but you need something a bit more complicated.  Here's some untested code that should point you in the right direction:

```twig
{% set type1 = [] %}
{% set type2 = [] %}
{% set type3 = [] %}

{% for item in my_pager.currentPageResults %}
    {% if item.type == 1 %}
        {% set type1 = type1|merge([item]) %}
    {% elseif item.type == 2 %}
        {% set type2 = type2|merge([item]) %}
    {% else %}
        {% set type3 = type3|merge([item]) %}
    {% endif %}
{% endfor %}

<div>
    <b>INFORMATION 1</b>
    {% for item in type1 %}
        {{ item.id }}<br>
    {% endfor %}
</div>
{# and so on for type2 and type3 #}
```

Hope this helps.

**Comment by nfouka** [comment]
Its Work ! Thank You !

**Comment by sampart** [comment]
Glad it's working.  Thanks for letting me know.
