### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by sampart** [whiteoctober/WhiteOctoberPagerfantaBundle#212]
Hi,

Sam here, one of the current maintainers of this project.

Given that we no longer use PHP in any of our active projects, it's becoming harder to give this plugin the time it needs.

Therefore, we're looking for new maintainer(s) for this project.

We'd like any new prospective maintainer to fork this project, and then once that fork has moved forward enough to give us confidence in your ownership, we would link to your fork prominently from the top of the README here, encouraging others to use it instead.

If you're interested, please go ahead and fork (if you haven't already) and start work!  If you've forked and would like others to help you, feel free to reply in this issue with details of your fork.

Please do reply here if you have questions.  Thanks in anticipation.

**Comment by sampart** [comment]
It's worth noting that a new fork needn't commit to supporting all versions of PHP/Symfony that this version does.  We're very happy to simply say "if you're using Symfony > x, see this new fork".

(See related discussion [here](https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/pull/217) about Symfony 5.)

**Comment by sampart** [comment]
We now signpost https://github.com/BabDev/BabDevPagerfantaBundle

**Comment by sampart** [comment]
@mbabker As you may have seen from my comment on the Pagerfanta repo itself, at some point the `whiteoctober` organisation will be deleted, along with this repo. Before that point, your repo - which is currently a fork of this one - will be updated to become the "root" (parent) repository. There's nothing you need to do - this is just FYI - but do let me know if you have any questions. Thanks again for your maintainership.

**Comment by mbabker** [comment]
> at some point the `whiteoctober` organisation will be deleted, along with this repo

You might want to archive this repository somewhere else instead of completely deleting it (and update Composer to point to that).  It's still getting [a larger number of installs](https://packagist.org/packages/white-october/pagerfanta-bundle/stats) than [my fork](https://packagist.org/packages/babdev/pagerfanta-bundle/stats), so deleting it would be somewhat catastrophic to the ecosystem (I know Sylius is still in the middle of fully migrating over having done some of the migration work to help them and for my clients' needs and that's probably one of the larger public facing projects involved here).

**Comment by sampart** [comment]
Thanks for the feedback and for suggestions about a better approach here. Moving this repo and updating composer sounds like the way to go, rather than changing the root (it'll probably be clearer what's going on if this one remains the root even in its new location). I'll look into getting this moved and will keep you updated.

**Comment by sampart** [comment]
For [Pagerfanta itself](https://github.com/whiteoctober/Pagerfanta), changing the root should be sufficient, however, as `pagerfanta/pagerfanta` in Packagists already points to your fork.

**Comment by sampart** [comment]
I've transferred this now. Thanks again for preventing me being too naive with the migration strategy here!
