### ISSUE TITLE
The package doesn't support the Symfony 5.

### ISSUE THREAD

**Issue by qg0** [whiteoctober/WhiteOctoberPagerfantaBundle#220]
The package doesn't support the Symfony 5.

**Comment by sampart** [comment]
Thanks for your comment, @qg0. Symfony 5 support is being discussed in PR #217, but I'll leave this issue open too until we've resolved it.

**Comment by sampart** [comment]
Hi again @qg0.  You may be interested in this maintained fork: https://github.com/BabDev/BabDevPagerfantaBundle.  See the PR I linked to for details.  Thanks
