### ISSUE TITLE
Supply a view which would actually use Twig for rendering

### ISSUE THREAD

**Issue by rimas-kudelis** [whiteoctober/WhiteOctoberPagerfantaBundle#225]
It's kinda a shame that Pagerfanta cannot be styled with native Twig templates, and php classes have to be created instead. I think this bundle could provide such a view. This is a feature request for that.

Note: yes I know that this project is not actively maintained at the moment. It's still better to have this idea laid out than not. :)

**Comment by mbabker** [comment]
👋

If you log this onto [my fork](https://github.com/BabDev/BabDevPagerfantaBundle), I can take a look at how feasible this might be.  The [`Pagerfanta\View\ViewInterface`](https://github.com/whiteoctober/Pagerfanta/blob/v2.1.3/src/Pagerfanta/View/ViewInterface.php) only cares that the `render()` method returns a string, so in theory it's possible to create a `TwigView` implementation that ignores the PHP `Pagerfanta\View\Template\TemplateInterface` objects and just renders a given Twig template (which, would probably be structured like a overly simplified version of Symfony's form themes that way one could use Twig's native template inheritance and customize different blocks).

**Comment by rimas-kudelis** [comment]
Yep, I've looked at ViewInterface and TemplateInterface as well and my conclusion was pretty much the same. I'm actually surprised noone has done this yet. Makes me suspect that perhaps overall speed is affected or something.

**Comment by rimas-kudelis** [comment]
Closing as fixed by  BabDev/BabDevPagerfantaBundle#2.
