### ISSUE TITLE
_route_params returns null in edge case

### ISSUE THREAD

**Issue by calumbrodie** [whiteoctober/WhiteOctoberPagerfantaBundle#62]
Similar to Issue #32 (but using the correct version of symfony).

I'm finding in Symfony 2.2 that there is a circumstance where $request->attributes->get('_route_params') does in fact return null. (and the merge error happens).

If rendering a fragment in twig, which calls a controller (and that controller ends up calling this extension), then the request attributes in that situation don't have a '_route_params' attribute set.

I'm guessing the break happened around this time:
http://symfony.com/blog/new-in-symfony-2-2-the-new-fragment-sub-framework

It think that the check for the 'internal' route is incorrect and an exception should be (legitimately) thrown.

The check should be against the 'strategy' option?

**Comment by jpass** [comment]
This always happens if we forward to action that later uses pagerfanta, as subrequest has no information about route: https://github.com/symfony/symfony/issues/5804

**Comment by justinhilles** [comment]
I ran into this problem again, rendering an embedded controller with pagerfanta in the template, As a temp solution I get the master request current route and pass it to pager fanta:

In Controller:
```php
            $request = $this->container->get('request_stack')->getParentRequest();

            $route = $request->get('_route');
```

In View:
```twig
{{ pagerfanta(pager, 'twitter_bootstrap3', {'routeName' : route }) }}
```

Working great at the moment, but id like to not have to. But i cant think of a more elegant way to do this
