### ISSUE TITLE
fix bug when routeName is passed as params into pagerfanta twig function

### ISSUE THREAD

**Issue by lsroudi** [whiteoctober/WhiteOctoberPagerfantaBundle#90]
hi
in this situation : 
``` html+jinja
{% if pager.haveToPaginate %}
    {{ pagerfanta(pager, 'twitter_bootstrap3_translated', {'routeName': 'search_annonces_1'},{'routeParams' : { 'v': 'keyword'  }}) }}
{% endif %}
```
we suppose inject keyword in pagination such a params route like this
/q=keyword&l=
but pagerfanta still generate route as 
/q=&l=

this happen when routeName is passed as params into pagerfanta twig function

**Comment by pablodip** [comment]
That is because the `routeParams` option should be passed into the third argument, alongside the `routeName` option.

**Comment by eloipoch** [comment]
Just change the code to:

```php
{% if pager.haveToPaginate %}
    {{ pagerfanta(pager, 'twitter_bootstrap3_translated', {'routeName': 'search_annonces_1', 'routeParams' : { 'v': 'keyword'}})}}
{% endif %}
