### ISSUE TITLE
please tag the lib

### ISSUE THREAD

**Issue by cordoval** [whiteoctober/WhiteOctoberPagerfantaBundle#93]

**Comment by richsage** [comment]
@pablodip can you organise a new release please?

**Comment by shirshir** [comment]
:+1:

**Comment by sinamt** [comment]
@pablodip could we get a new release please? We're bumping into https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/pull/102 which is fixed in master. Thanks.

**Comment by richsage** [comment]
v1.0.3 has been created.
